micronaut:
  application:
    name: micronautguide
  email:
    from:
      email: ${FROM_EMAIL:''} # <1>
      name: ${FROM_NAME:''} # <2>
smtp:
  password: ${SMTP_PASSWORD:''} # <3>
  user: ${SMTP_USER:''} # <4>
javamail:
  properties:
    mail:
      smtp:
        port: 587
        auth: true
        starttls:
          enable: true
        host: ${SMTP_HOST:''} # <5>
netty:
  default:
    allocator:
      max-order: 3
