micronaut:
  application:
    name: micronautguide
  email:
    from:
      email: 
      name: 
smtp:
  password: 
  user: 
javamail:
  properties:
    mail:
      smtp:
        port: 587
        auth: true
        starttls:
          enable: true
        host: 
netty:
  default:
    allocator:
      max-order: 3
